### PR TITLE
NVML: Handle Unsupported GPU Serial

### LINKED ISSUE #16: Handle GPUs that lack full NVML Support
Nvidia NVML does not support non-Tesla product very well. Problems are known with [mobile](https://github.com/NVIDIA/nvidia-docker/issues/40#issuecomment-175255477) cards and even [Quadro cards](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2704#issuecomment-428897871). (Reported as RFE to Nvidia as Bug ID 2417658.)

Anyway, this can lead to `cuda_memtest` throwing an [`[NVML] Error: Not supported`](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2704#issuecomment-428901569) (in [`nvmlDeviceGetSerial`](https://github.com/ComputationalRadiationPhysics/cuda_memtest/blob/7a585d504831431d0e95ff00d0217181201dbb12/misc.cpp#L33)) exception which we should catch.

### PR DESCRIPTION
**Pull request by ax3l**
Catch errors if NVML can not query the device serial number, e.g. on Quadro, Mobile or other product lines.

Fix #16

### CODE REVIEW

File: misc.cpp [hunk 1]
```diff
@@ -26,11 +26,22 @@ void update_temperature(void)
...
-    nvmlDevice_t devHandle;
-    NVML_CHECK(nvmlDeviceGetHandleByIndex( devIdx, &devHandle ));
+    try
+    {
+        nvmlDevice_t devHandle;
+        NVML_CHECK(nvmlDeviceGetHandleByIndex( devIdx, &devHandle ));
 
-    unsigned int serialLength = NVML_DEVICE_SERIAL_BUFFER_SIZE;
-    NVML_CHECK(nvmlDeviceGetSerial( devHandle, serial, serialLength ));
+        unsigned int serialLength = NVML_DEVICE_SERIAL_BUFFER_SIZE;
```
Comment (ax3l) [inline misc.cpp:34]: constant is [30](https://docs.nvidia.com/deploy/nvml-api/group__nvmlConstants.html#group__nvmlConstants_1gca7e1ec7e1c14c01b7980b38188245d0)

Safe [`std::strncpy`](https://en.cppreference.com/w/cpp/string/byte/strncpy) used below with a string that is 28 chars and is therefore usually not cropped. Null-added manuall in case it gets cropped.

**Review by psychocoderHPC — APPROVED** [review]
